#!/usr/bin/env bash
# servers are the pieces of software generating HTML pages
# installing one, nginx

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'Nginx HTTP'
sh -c 'echo "Hello World!" >> /var/www/html/index.html'
service nginx restart
