#!/usr/bin/env bash
# installing the ufw firewall and setup a few rules on web-01

sudo apt install -y ufw
sudo ufw default allow outgoing
sudo ufw default deny incoming
sudo ufw allow ssh
sudo ufw allow https
sudo ufw allow http
echo "y" | ufw enable
